// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.
// Run `npm run optimize:images` to regenerate.

export interface ResponsiveImage {
  /** intrinsic width of the full (capped) image */
  w: number;
  /** intrinsic height of the full (capped) image */
  h: number;
  /** path to the small grid thumbnail */
  thumb: string;
  thumbW: number;
  thumbH: number;
}

export const imageManifest: Record<string, ResponsiveImage> = {
  "/images/gallery/cooking.webp": {"w":1536,"h":2048,"thumb":"/images/gallery/cooking-thumb.webp","thumbW":576,"thumbH":768},
  "/images/gallery/danfam.webp": {"w":1440,"h":1080,"thumb":"/images/gallery/danfam-thumb.webp","thumbW":768,"thumbH":576},
  "/images/gallery/dough.webp": {"w":1476,"h":2048,"thumb":"/images/gallery/dough-thumb.webp","thumbW":554,"thumbH":768},
  "/images/gallery/frisbee.webp": {"w":2048,"h":1365,"thumb":"/images/gallery/frisbee-thumb.webp","thumbW":768,"thumbH":512},
  "/images/gallery/tbell.webp": {"w":1926,"h":2048,"thumb":"/images/gallery/tbell-thumb.webp","thumbW":722,"thumbH":768},
  "/images/gallery/twon.webp": {"w":2048,"h":1536,"thumb":"/images/gallery/twon-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/cooking/bak1.webp": {"w":1536,"h":2048,"thumb":"/images/plp/cooking/bak1-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/cooking/bowl.webp": {"w":1536,"h":2048,"thumb":"/images/plp/cooking/bowl-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/cooking/bowl2.webp": {"w":1536,"h":2048,"thumb":"/images/plp/cooking/bowl2-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/cooking/bowl3.webp": {"w":1536,"h":2048,"thumb":"/images/plp/cooking/bowl3-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/cooking/food4.webp": {"w":1885,"h":2048,"thumb":"/images/plp/cooking/food4-thumb.webp","thumbW":707,"thumbH":768},
  "/images/plp/cooking/noodle.webp": {"w":2048,"h":2028,"thumb":"/images/plp/cooking/noodle-thumb.webp","thumbW":768,"thumbH":760},
  "/images/plp/cooking/rolls.webp": {"w":2048,"h":1536,"thumb":"/images/plp/cooking/rolls-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/cooking/soup.webp": {"w":1939,"h":2048,"thumb":"/images/plp/cooking/soup-thumb.webp","thumbW":727,"thumbH":768},
  "/images/plp/cooking/sushi.webp": {"w":1536,"h":2048,"thumb":"/images/plp/cooking/sushi-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/fam/DanGrampFam.webp": {"w":2048,"h":1536,"thumb":"/images/plp/fam/DanGrampFam-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/fam/aurassert.webp": {"w":1536,"h":2048,"thumb":"/images/plp/fam/aurassert-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/fam/danFamEat.webp": {"w":2048,"h":1536,"thumb":"/images/plp/fam/danFamEat-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/fam/fam10.webp": {"w":946,"h":2048,"thumb":"/images/plp/fam/fam10-thumb.webp","thumbW":355,"thumbH":768},
  "/images/plp/fam/fam12.webp": {"w":2048,"h":946,"thumb":"/images/plp/fam/fam12-thumb.webp","thumbW":768,"thumbH":355},
  "/images/plp/fam/fam3.webp": {"w":1080,"h":1440,"thumb":"/images/plp/fam/fam3-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/fam/fam4.webp": {"w":1200,"h":554,"thumb":"/images/plp/fam/fam4-thumb.webp","thumbW":768,"thumbH":355},
  "/images/plp/fam/fam5.webp": {"w":1440,"h":1080,"thumb":"/images/plp/fam/fam5-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/fam/fam7.webp": {"w":640,"h":480,"thumb":"/images/plp/fam/fam7-thumb.webp","thumbW":640,"thumbH":480},
  "/images/plp/fam/fam8.webp": {"w":2048,"h":1536,"thumb":"/images/plp/fam/fam8-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/fam/fam9.webp": {"w":1536,"h":2048,"thumb":"/images/plp/fam/fam9-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/fam/lucas.webp": {"w":1536,"h":2048,"thumb":"/images/plp/fam/lucas-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/fam/lucas2.webp": {"w":1536,"h":2048,"thumb":"/images/plp/fam/lucas2-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/friends/alan.webp": {"w":2048,"h":1536,"thumb":"/images/plp/friends/alan-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/friends/bid.webp": {"w":1536,"h":2048,"thumb":"/images/plp/friends/bid-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/friends/danAlanPack.webp": {"w":1536,"h":2048,"thumb":"/images/plp/friends/danAlanPack-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/friends/dhan.webp": {"w":1616,"h":1080,"thumb":"/images/plp/friends/dhan-thumb.webp","thumbW":768,"thumbH":513},
  "/images/plp/friends/friend1.webp": {"w":946,"h":2048,"thumb":"/images/plp/friends/friend1-thumb.webp","thumbW":355,"thumbH":768},
  "/images/plp/friends/friend2.webp": {"w":946,"h":2048,"thumb":"/images/plp/friends/friend2-thumb.webp","thumbW":355,"thumbH":768},
  "/images/plp/friends/montreal1.webp": {"w":2048,"h":1536,"thumb":"/images/plp/friends/montreal1-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/friends/montreal2.webp": {"w":2048,"h":1536,"thumb":"/images/plp/friends/montreal2-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/friends/montreal3.webp": {"w":2048,"h":1536,"thumb":"/images/plp/friends/montreal3-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/friends/montreal4.webp": {"w":2048,"h":1536,"thumb":"/images/plp/friends/montreal4-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/friends/phili_friends.webp": {"w":2048,"h":1536,"thumb":"/images/plp/friends/phili_friends-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/friends/point.webp": {"w":2048,"h":1536,"thumb":"/images/plp/friends/point-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/friends/pointban.webp": {"w":1536,"h":2048,"thumb":"/images/plp/friends/pointban-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/friends/vish.webp": {"w":2048,"h":1536,"thumb":"/images/plp/friends/vish-thumb.webp","thumbW":768,"thumbH":576},
  "/images/plp/frisbee/frisbee1.webp": {"w":2048,"h":1429,"thumb":"/images/plp/frisbee/frisbee1-thumb.webp","thumbW":768,"thumbH":536},
  "/images/plp/frisbee/frisbee11.webp": {"w":2048,"h":1542,"thumb":"/images/plp/frisbee/frisbee11-thumb.webp","thumbW":768,"thumbH":578},
  "/images/plp/frisbee/frisbee12.webp": {"w":2048,"h":1365,"thumb":"/images/plp/frisbee/frisbee12-thumb.webp","thumbW":768,"thumbH":512},
  "/images/plp/frisbee/frisbee13.webp": {"w":2048,"h":1365,"thumb":"/images/plp/frisbee/frisbee13-thumb.webp","thumbW":768,"thumbH":512},
  "/images/plp/frisbee/frisbee14.webp": {"w":2048,"h":1365,"thumb":"/images/plp/frisbee/frisbee14-thumb.webp","thumbW":768,"thumbH":512},
  "/images/plp/frisbee/frisbee2.webp": {"w":1594,"h":2048,"thumb":"/images/plp/frisbee/frisbee2-thumb.webp","thumbW":598,"thumbH":768},
  "/images/plp/frisbee/frisbee4.webp": {"w":1337,"h":2048,"thumb":"/images/plp/frisbee/frisbee4-thumb.webp","thumbW":501,"thumbH":768},
  "/images/plp/frisbee/frisbee5.webp": {"w":2048,"h":1454,"thumb":"/images/plp/frisbee/frisbee5-thumb.webp","thumbW":768,"thumbH":545},
  "/images/plp/frisbee/frisbee6.webp": {"w":2048,"h":1365,"thumb":"/images/plp/frisbee/frisbee6-thumb.webp","thumbW":768,"thumbH":512},
  "/images/plp/frisbee/frisbee7.webp": {"w":2048,"h":1488,"thumb":"/images/plp/frisbee/frisbee7-thumb.webp","thumbW":768,"thumbH":558},
  "/images/plp/frisbee/frisbee8.webp": {"w":2048,"h":1365,"thumb":"/images/plp/frisbee/frisbee8-thumb.webp","thumbW":768,"thumbH":512},
  "/images/plp/frisbee/frisbee9.webp": {"w":2048,"h":1392,"thumb":"/images/plp/frisbee/frisbee9-thumb.webp","thumbW":768,"thumbH":522},
  "/images/plp/sourdough/sour1.webp": {"w":1200,"h":2048,"thumb":"/images/plp/sourdough/sour1-thumb.webp","thumbW":450,"thumbH":768},
  "/images/plp/sourdough/sour10.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour10-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour11.webp": {"w":1591,"h":2048,"thumb":"/images/plp/sourdough/sour11-thumb.webp","thumbW":597,"thumbH":768},
  "/images/plp/sourdough/sour12.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour12-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour13.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour13-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour14.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour14-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour15.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour15-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour16.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour16-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour2.webp": {"w":2048,"h":2005,"thumb":"/images/plp/sourdough/sour2-thumb.webp","thumbW":768,"thumbH":752},
  "/images/plp/sourdough/sour3.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour3-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour4.webp": {"w":2048,"h":1921,"thumb":"/images/plp/sourdough/sour4-thumb.webp","thumbW":768,"thumbH":720},
  "/images/plp/sourdough/sour5.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour5-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour6.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour6-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour7.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour7-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour8.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour8-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/sourdough/sour9.webp": {"w":1536,"h":2048,"thumb":"/images/plp/sourdough/sour9-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/tacobell/tbell1.webp": {"w":2048,"h":1240,"thumb":"/images/plp/tacobell/tbell1-thumb.webp","thumbW":609,"thumbH":369},
  "/images/plp/tacobell/tbell2.webp": {"w":1984,"h":2048,"thumb":"/images/plp/tacobell/tbell2-thumb.webp","thumbW":744,"thumbH":768},
  "/images/plp/tacobell/tbell3.webp": {"w":2048,"h":1076,"thumb":"/images/plp/tacobell/tbell3-thumb.webp","thumbW":768,"thumbH":404},
  "/images/plp/tacobell/tbell4.webp": {"w":1849,"h":2048,"thumb":"/images/plp/tacobell/tbell4-thumb.webp","thumbW":693,"thumbH":768},
  "/images/plp/tacobell/tbell5.webp": {"w":1536,"h":2048,"thumb":"/images/plp/tacobell/tbell5-thumb.webp","thumbW":576,"thumbH":768},
  "/images/plp/tacobell/tbell6.webp": {"w":1878,"h":2048,"thumb":"/images/plp/tacobell/tbell6-thumb.webp","thumbW":704,"thumbH":768},
};

/**
 * Build responsive <img> props for a grid image. Defaults `src` to the small
 * thumbnail and offers the full image as a larger srcSet candidate, so grids load
 * tiny images while high-DPR / large slots can still upgrade. Falls back to the
 * original src for any image not in the manifest.
 */
export function responsive(src: string, sizes: string) {
  const m = imageManifest[src];
  if (!m) return { src, sizes };
  return {
    src: m.thumb,
    srcSet: `${m.thumb} ${m.thumbW}w, ${src} ${m.w}w`,
    sizes,
  };
}
